## YAML Template.
---
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 03d32a70895640c0c70c
            clientSecret: adad65091cdba1a85f0f019e1b9331de3f3247ff
# ...